name: Pipeline

on: [push]

jobs:
  build:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    steps:
      - uses: actions/checkout@v1

      - name: Cache batect
        uses: actions/cache@v1
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Lint code
        run: ./batect lint
